name: Check For Protected File Changes

on:
  workflow_dispatch:
  pull_request_target:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Print the SHA of the head ref
      run: echo $(git rev-parse $GITHUB_HEAD_REF)

    - name: Print the SHA of the base ref
      run: echo $(git rev-parse $GITHUB_BASE_REF)

    - name: Check for file changes using Python
      run: python .github/scripts/git_protect.py ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.base.sha }}
