name: Check For Protected File Changes

on:
  workflow_dispatch:
  pull_request_target:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Print the current working directory
      run: pwd

    - name: Print the current working directory
      run: echo $GITHUB_SHA

    - name: Print the current working directory
      run: echo $GITHUB_HEAD_REF

    - name: Check for file changes using Python
      run: python .github/scripts/git_protect.py $GITHUB_SHA $GITHUB_HEAD_REF
